stages:
  - build
  - deploy

variables:
  NODE_VERSION: "21"

build_job:
  stage: build
  image: node:${NODE_VERSION}-alpine
  script:
    - echo "Verwende Node.js Version ${NODE_VERSION}"
    - npm install
    - npm run build --if-present
  artifacts:
    paths:
      - dist/videoflix_frontend/browser

deploy_job:
  stage: deploy
  image: curlimages/curl:latest
  dependencies:
    - build_job
  script:
    - echo "Starte den FTPS-Upload..."
    - echo "$ALEXHOST"
    - echo "$ALEXUSERNAME"
    - curl --ssl-reqd -T ./dist/videoflix_frontend/browser/ --user "$ALEXUSERNAME:$ALEXPASSWORD" "$ALEXHOST"
  only:
    - alex
