stages:
  - build
  - deploy

variables:
  NODE_VERSION: "21"

build_job:
  stage: build
  image: node:${NODE_VERSION}-alpine
  script:
    - echo "Verwende Node.js Version ${NODE_VERSION}"
    - npm install
    - npm run build --if-present
  artifacts:
    paths:
      - dist/videoflix_frontend/browser

deploy_job:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  dependencies:
    - build_job
  script:
    - echo "Starte den FTPS-Upload..."
    - echo "$ALEXHOST"
    - for file in ./dist/videoflix_frontend/browser/*; do
        curl --ftp-ssl --ssl-reqd --ftp-create-dirs --user "$ALEXUSERNAME:$ALEXPASSWORD" "$ALEXHOST" -T "$file";
      done
  only:
    - alex