stages:
  - build
  - deploy

variables:
  NODE_VERSION: "21"  # Definiert die Node.js-Version

build_job:
  stage: build
  image: node:${NODE_VERSION}-alpine
  script:
    - echo "Verwende Node.js Version ${NODE_VERSION}"
    - npm install
    - npm run build --if-present
  artifacts:
    paths:
      - dist/videoflix_frontend/browser  # Bereitstellen für den Deploy-Job

deploy_job:
  stage: deploy
  image: curlimages/curl:latest  # Für das FTP-Upload-Script
  dependencies:
    - build_job
  script:
    - echo "Starte den FTPS-Upload..."
    - curl -T ./dist/videoflix_frontend/browser/ --user "$ALEXUSERNAME:$ALEXPASSWORD" ftps://$ALEXHOST/
  only:
    - alex  # Ausführen bei Push auf "alex"-Branch test