stages:
  - build
  - deploy

variables:
  NODE_VERSION: "21"

build_job:
  stage: build
  image: node:${NODE_VERSION}-alpine
  script:
    - echo "Verwende Node.js Version ${NODE_VERSION}"
    - npm install
    - npm run build --if-present
  artifacts:
    paths:
      - dist/videoflix_frontend/browser

stages:
  - build
  - deploy

variables:
  NODE_VERSION: "21"

build_job:
  stage: build
  image: node:${NODE_VERSION}-alpine
  script:
    - echo "Verwende Node.js Version ${NODE_VERSION}"
    - npm install
    - npm run build --if-present
  artifacts:
    paths:
      - dist/videoflix_frontend/browser

deploy_job:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
  script:
    - echo "Starte den SSH-Upload..."
    - scp -r dist/videoflix_frontend/browser/* "$SSH_USER@$SSH_ALEX_HOST:$REMOTE_PATH"
  only:
    - alex

